<?xml version="1.0" encoding="utf-8"?><Database Name="sistemadb" Class="SampleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-E860BKA;Initial Catalog=sistemadb;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="sistemadbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cidades" Member="Cidades">
    <Type Name="Cidade">
      <Column Name="idCidade" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="NVarChar(350) NOT NULL" CanBeNull="false" />
      <Column Name="sigla" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Pessoas" Member="Pessoas">
    <Type Name="Pessoa">
      <Column Name="idPessoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="telefone" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="obs" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
</Database>